theme = "cutiepro"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
default-line-ending = "lf"
line-number = "relative"
mouse = false
scroll-lines = 0
# scrolloff = 10
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "spinner",
]
center = [
  "read-only-indicator",
  "file-name",
  "file-modification-indicator",
  "spacer",
  "version-control",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding",
]

[keys.normal]
ret = ["open_below", "normal_mode"]
S-ret = ["open_above", "normal_mode"]

[keys.insert]
C-backspace = [
  "normal_mode",
  "move_prev_word_start",
  "delete_selection_noyank",
  "insert_mode",
]
C-del = [
  "normal_mode",
  "move_next_word_end",
  "delete_selection_noyank",
  "insert_mode",
]
